[package]
name = "rudp2p"
description = "Library to exchange P2P messages with UDP protocol"
version = "0.2.2"
authors = ["Gr√©gory Tardivel"]
repository = "https://github.com/gr3gdev/rudp2p"
edition = "2021"
license-file = "LICENSE"
keywords = ["P2P", "UDP"]
categories = ["network-programming", "web-programming"]
exclude = ["/features", "/.github", "/target"]

[lib]
name = "rudp2plib"
path = "src/lib.rs"
doc = true

[[test]]
name = "peer"
harness = false

[dependencies]
openssl = "0.10"

[dev-dependencies]
openssl-sys = "0.9"
cucumber = "0.19"
futures = "0.3"
